name: Crear o actualizar rama de cliente
description: Crear o actualizar una rama de cliente a partir de un archivo en .clients/

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre del archivo de cliente en .clients/'
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-24.04
    outputs:
      new_branch: ${{ steps.determine_branch_name.outputs.new_branch }}
      create_pr: ${{ steps.determine_branch_name.outputs.new_branch != format('clients/{0}', github.event.inputs.branch_name) }}
    steps:
      - name: Checkout del repositorio principal
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Validar existencia del archivo del cliente en .clients/
        run: |
          if [ ! -f ".clients/${{ github.event.inputs.branch_name }}" ]; then
            echo "Error: El archivo .clients/${{ github.event.inputs.branch_name }} no existe. Abortando."
            exit 1
          fi

      - name: Generar nombre para la nueva rama
        id: determine_branch_name
        run: |
          if git ls-remote --exit-code --heads origin "clients/${{ github.event.inputs.branch_name }}"; then
            echo "La rama existe, se usará nombre con sufijo."
            commit_ref=$(git rev-parse --short origin/main)
            NEW_BRANCH="clients/${{ github.event.inputs.branch_name }}_${commit_ref}"
          else
            NEW_BRANCH="clients/${{ github.event.inputs.branch_name }}"
          fi
          echo "NEW_BRANCH=${NEW_BRANCH}"
          echo "new_branch=${NEW_BRANCH}" >> $GITHUB_OUTPUT

      - name: Configurar git para el usuario actual
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Crear nueva rama y realizar commit inicial
        run: |
          cp ".clients/${{ github.event.inputs.branch_name }}" "/tmp/${{ github.event.inputs.branch_name }}"
          NEW_BRANCH="${{ steps.determine_branch_name.outputs.new_branch }}"
          if [[ "$NEW_BRANCH" == "${{ github.event.inputs.branch_name }}" ]]; then
            git checkout "origin/clients/${{ github.event.inputs.branch_name }}"
            git checkout -b "$NEW_BRANCH"
          else
            git switch --orphan "$NEW_BRANCH"
          fi
          while IFS= read -r file || [ -n "$file" ]; do
            git checkout origin/main -- "$file" || echo "Advertencia: Archivo $file no encontrado en main"
            git add "$file"
          done < "/tmp/${{ github.event.inputs.branch_name }}"
          git commit -m "Initial commit for: $NEW_BRANCH"

      - name: Subir cambios a la nueva rama
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.determine_branch_name.outputs.new_branch }}
          force: true

  create_pr:
    needs: create_branch
    if: ${{ needs.create_branch.outputs.create_pr == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout de la rama base
        uses: actions/checkout@v4
        with:
          ref: "clients/${{ github.event.inputs.branch_name }}"
          fetch-depth: 0
      - name: Crear Pull Request utilizando GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "PR: ${{ needs.create_branch.outputs.new_branch }} -> ${{ github.event.inputs.branch_name }}"
          PR_BODY: "Automatically created pull request for branch ${{ needs.create_branch.outputs.new_branch }}"
          FROM: ${{ needs.create_branch.outputs.new_branch }}
          TO: ${{ github.event.inputs.branch_name }}
        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base "$FROM" --head "$TO" --assignee "${{ github.actor }}" --reviewer "${{ github.actor }}"

