name: Crear rama dedicada a cliente

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre del archivo de cliente en .clients/'
        required: true

jobs:
  create_dedicated_client_branch:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout completo del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar existencia del archivo cliente y que no exista la rama
        run: |
          if [ ! -f ".clients/${{ github.event.inputs.branch_name }}" ]; then
            echo "Error: El archivo .clients/${{ github.event.inputs.branch_name }} no existe. Abortando."
            exit 1
          fi
          # Verificar que la rama no existe 
          if git ls-remote --exit-code --heads origin "${{ github.event.inputs.branch_name }}"; then
            echo "Error: La rama ${{ github.event.inputs.branch_name }} ya existe. Abortando."
            exit 1
          fi

      - name: Set up git configuration
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Crear rama huérfana y commit inicial
        run: |
          # Copiar el archivo de cliente a un directorio temporal para preservarlo
          cp ".clients/${{ github.event.inputs.branch_name }}" "/tmp/${{ github.event.inputs.branch_name }}"
          # Crear la rama huérfana y resetear el índice
          git checkout --orphan "${{ github.event.inputs.branch_name }}"
          git reset --hard
          # Leer el archivo copiado línea por línea e incluir la última línea 
          while IFS= read -r file || [ -n "$file" ]; do
            git checkout main -- "$file"
          done < "/tmp/${{ github.event.inputs.branch_name }}"
          # Realizar el commit inicial
          git commit -m "Initial commit for: ${{ github.event.inputs.branch_name }}"
      
      - name: Push files to the new branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch_name }}
