name: Crear rama dedicada a cliente

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Nombre del archivo de cliente en .clients/'
        required: true

jobs:
  create_branch:
    runs-on: ubuntu-24.04
    outputs:
      new_branch: ${{ steps.determine_branch_name.outputs.new_branch }}
      is_new_branch: ${{ steps.determine_branch_name.outputs.new_branch != github.event.inputs.branch_name }}
    steps:
      - name: Checkout completo del repositorio
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Verificar existencia del archivo cliente en .clients/
        run: |
          if [ ! -f ".clients/${{ github.event.inputs.branch_name }}" ]; then
            echo "Error: El archivo .clients/${{ github.event.inputs.branch_name }} no existe. Abortando."
            exit 1
          fi

      - name: Determinar nombre de rama
        id: determine_branch_name
        run: |
          if git ls-remote --exit-code --heads origin "${{ github.event.inputs.branch_name }}"; then
            echo "La rama existe, se usará nombre con sufijo."
            commit_ref=$(git rev-parse --short origin/main)
            NEW_BRANCH="${{ github.event.inputs.branch_name }}_${commit_ref}"
          else
            NEW_BRANCH="${{ github.event.inputs.branch_name }}"
          fi
          echo "NEW_BRANCH=${NEW_BRANCH}"
          echo "new_branch=${NEW_BRANCH}" >> $GITHUB_OUTPUT

      - name: Set up git configuration
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Crear rama de cliente y commit inicial
        run: |
          cp ".clients/${{ github.event.inputs.branch_name }}" "/tmp/${{ github.event.inputs.branch_name }}"
          # git fetch --all
          NEW_BRANCH="${{ steps.determine_branch_name.outputs.new_branch }}"
          if [[ "$NEW_BRANCH" == *_* ]]; then
            git checkout "origin/${{ github.event.inputs.branch_name }}"
            git checkout -b "$NEW_BRANCH"
          else
            git switch --orphan "$NEW_BRANCH"
          fi
          while IFS= read -r file || [ -n "$file" ]; do
            git checkout origin/main -- "$file" || echo "Advertencia: Archivo $file no encontrado en main"
            git add "$file"
          done < "/tmp/${{ github.event.inputs.branch_name }}"
          git commit -m "Initial commit for: $NEW_BRANCH"

      - name: Push files to the new branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.determine_branch_name.outputs.new_branch }}
          force: true

  create_pr:
    needs: create_branch
    if: ${{ needs.create_branch.outputs.is_new_branch == 'true' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Create Pull Request using GitHub API
        id: create_pr
        run: |
          PR_TITLE="Pull Request for branch ${{ needs.create_branch.outputs.new_branch }}"
          PR_BODY="Automatically created pull request for branch ${{ needs.create_branch.outputs.new_branch }}."
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls"
          PAYLOAD=$(jq -n \
            --arg title "$PR_TITLE" \
            --arg head "${{ needs.create_branch.outputs.new_branch }}" \
            --arg base "${{ github.event.inputs.branch_name }}" \
            --arg body "$PR_BODY" \
            '{title: $title, head: $head, base: $base, body: $body}')
          echo "Creating pull request with payload: $PAYLOAD"
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               $API_URL

